[package]
name = "shrek_superslam"
version = "0.1.0"
authors = ["alex <kirby@cpan.org>"]
edition = "2018"

[[bin]]
name = "s3_extract"
path = "src/extract/main.rs"

[[bin]]
name = "s3_repackage"
path = "src/repackage/main.rs"

[dependencies]
byteorder = "1.3.2"
